"""add_component_fields_and_seeds

Revision ID: 8b98ad57ae8d
Revises: 
Create Date: 2025-09-30 21:09:30.076357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b98ad57ae8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('props_schema', sa.JSON(), nullable=True))
    op.add_column('components', sa.Column('example_props', sa.JSON(), nullable=True))
    op.add_column('components', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('components', sa.Column('min_span', sa.Integer(), nullable=True))
    op.add_column('components', sa.Column('max_span', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'max_span')
    op.drop_column('components', 'min_span')
    op.drop_column('components', 'category')
    op.drop_column('components', 'example_props')
    op.drop_column('components', 'props_schema')
    # ### end Alembic commands ###

